# Generated by Django 3.2.8 on 2021-10-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0002_auto_20211018_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
